name: openai_dart_dio
description: ｜
  `openai_dart_dio` is a type-safe Dart library for interacting with the OpenAI API, built on the Dio HTTP client. It simplifies making requests to OpenAI services like GPT-3, DALL·E, and Codex, with automatic JSON serialization and robust error handling. The library ensures a streamlined and efficient integration, offering strong type safety and easy-to-use API calls for Dart and Flutter developers.
version: 2.0.1
homepage: https://github.com/wilinz/openai_dart_dio
repository: https://github.com/wilinz/openai_dart_dio

environment:
  sdk: ">=3.0.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  dio: ^5.3.3
  fetch_client: ^1.0.2
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.3.1
  copy_with_extension: ^6.0.1
  equatable: ^2.0.5
  autoequal: ^0.9.1
  http: ^1.3.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  json5_model: ^4.1.0
  copy_with_extension_gen: ^6.0.1
  autoequal_gen: ^0.9.5

index_generator:
  exclude:
    - '**.g.dart'
  # Define the paths of the folders in which to generate the index files
  libraries:
    - directory_path: lib